"""Regenerate the bundled cube and checker texture using only Python's standard library."""

from pathlib import Path
import struct
import zlib


OUTPUT = Path(__file__).resolve().parents[1] / "res" / "demo"


def cube():
    # Each face has independent UVs and an outward normal; triangles wind anticlockwise.
    faces = [
        ((0, 0, 1), [(-1, -1, 1), (1, -1, 1), (1, 1, 1), (-1, 1, 1)]),
        ((0, 0, -1), [(1, -1, -1), (-1, -1, -1), (-1, 1, -1), (1, 1, -1)]),
        ((1, 0, 0), [(1, -1, 1), (1, -1, -1), (1, 1, -1), (1, 1, 1)]),
        ((-1, 0, 0), [(-1, -1, -1), (-1, -1, 1), (-1, 1, 1), (-1, 1, -1)]),
        ((0, 1, 0), [(-1, 1, 1), (1, 1, 1), (1, 1, -1), (-1, 1, -1)]),
        ((0, -1, 0), [(-1, -1, -1), (1, -1, -1), (1, -1, 1), (-1, -1, 1)]),
    ]
    lines = ["# GAEngine demo cube. Generated by tools/generate_demo_assets.py; MIT licence.", "o DemoCube"]
    for _, vertices in faces:
        lines.extend("v {} {} {}".format(*v) for v in vertices)
    lines.extend(["vt 0 0", "vt 1 0", "vt 1 1", "vt 0 1"])
    lines.extend("vn {} {} {}".format(*normal) for normal, _ in faces)
    for i in range(len(faces)):
        start, normal = i * 4 + 1, i + 1
        for indices in ((0, 1, 2), (0, 2, 3)):
            lines.append("f " + " ".join(f"{start + j}/{j + 1}/{normal}" for j in indices))
    return ("\n".join(lines) + "\n").encode("ascii")


def png_chunk(kind, data):
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))


def checker():
    size = 128
    colours = ((35, 151, 166), (237, 232, 215))
    pixels = bytearray()
    for y in range(size):
        pixels.append(0)  # PNG filter: none
        for x in range(size):
            pixels.extend(colours[(x // 16 + y // 16) % 2])
    header = struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + png_chunk(b"IHDR", header)
            + png_chunk(b"IDAT", zlib.compress(bytes(pixels), 9)) + png_chunk(b"IEND", b""))


if __name__ == "__main__":
    OUTPUT.mkdir(parents=True, exist_ok=True)
    (OUTPUT / "cube.obj").write_bytes(cube())
    (OUTPUT / "checker.png").write_bytes(checker())
    print(f"Generated demo assets in {OUTPUT}")
